[package]
name = "nodejs_hw_mongodb"
version = "1.0.0"
edition = "2021"
description = "Rust equivalent of nodejs-hw-mongodb"
authors = ["Pavel_Paul <bpv358@gmail.com>"]
license = "ISC"
repository = "https://github.com/PavelSteep/nodejs-hw-mongodb"
homepage = "https://github.com/PavelSteep/nodejs-hw-mongodb#readme"

[dependencies]
actix-web = "4.5.1"         # Аналог Express.js для веб-сервера
dotenv = "0.15"            # Аналог пакета dotenv для загрузки переменных окружения
mongodb = "2.8.0"          # Библиотека MongoDB для Rust
serde = { version = "1.0", features = ["derive"] }  # Для сериализации данных
pino = "0.2.0"             # Аналог Pino для логирования (или можно использовать tracing)

[dev-dependencies]
tokio = { version = "1", features = ["full"] }  # Для асинхронных тестов
